# This workflow will build PRs submitted to the main branch.

name: 🚀 [DEV] Deploy

on:
  push:
    branches:
      - dev-001
    paths:
      - "apps/**"
      - "packages/**"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: 🚧 Build
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ "16.x" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 2

      - name: 🟢 Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 🛠️ Bootstrap Dependencies
        id: bootstrap-dependencies-with-cache
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: 🏗️ Build
        id: build-the-mono-repo
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_ENVIRONMENT='DEV'" >> .env.local
          yarn build

      - name: 🐱 Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  deploy:
    name: 🚀 Deploy
    if: github.repository_owner == 'brionmario' && github.event_name == 'push'
    needs: [ build ]
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ "16.x" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 👩‍🚀 Start Deployment
        id: deployment
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: start
          token: ${{ env.GITHUB_TOKEN }}
          env: ${{ fromJSON('["Production", "Preview"]')[github.ref != 'refs/heads/main'] }} 

      - name: ⬇️ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 2
          token: ${{ env.GITHUB_TOKEN }}

      - name: 🟢 Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 🛠️ Bootstrap Dependencies
        id: bootstrap-dependencies-with-cache
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: 🏗️ Build
        id: build-the-mono-repo
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_ENVIRONMENT='DEV'" >> .env.local
          yarn build

      - name: ▲ Deploy to Vercel
        id: deploy-to-vercel
        uses: amondnet/vercel-action@v20.0.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: ${{ fromJSON('["--development", ""]')[github.ref != 'refs/heads/main'] }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} 
          scope: ${{ secrets.VERCEL_ORG_ID}}
          working-directory: ./
          alias-domains: |
            dev.brionmario.com

      - name: 🏁 Finish Deployment
        id: finish-deployment
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ env.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: 🐱 Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
